---
  title: "Flow data pipeline"
author: "Ben Cowley"
output: 
  html_document:
  df_print: paged
toc: yes
toc_depth: '4'
# html_notebook:
#   code_folding: show
#   css: style.css
#   theme: yeti
#   toc: yes
pdf_document:
  toc: yes
toc_depth: '4'

---
  # Behavioral (CogCarSim) + FSS data
  
  ### Importing data
```{r setup}
# attach packages
library(RSQLite)
library(data.table)
library(magrittr)
library(tidyverse)
library(stringr)
library(purrr)
library(broom)
library(jsonlite)
library(DT)
library(lme4)
library(viridis)
library(here)
library(gghalves)
 
source(file.path(here(), 'R', 'utils.R'))
# set working directory, i.e. folder with data files
knitr::opts_knit$set(root.dir = normalizePath(file.path(here(), '..', 'data')))
# create an output dir for figures
odir <- file.path(here(), 'figures')
dir.create(odir, showWarnings = FALSE)
```

```{r data import}
# import the cogcarsim2 databases
tbls <- readCCSdb("cogcarsim2_2017.db")
tbl_blob = tbls$tbl_blob

sqlite.driver <- dbDriver("SQLite")
connection <- dbConnect(sqlite.driver,
                        dbname = paste0("cogcarsim2_2017.db"))

# get tables named blob, run, step
tables <- dbListTables(connection)
tbl_blob <- dbReadTable(connection, tables[1], row.names=NULL)
tbl_run <- dbReadTable(connection, tables[2], row.names=NULL)
tbl_step <- dbReadTable(connection, tables[3], row.names=NULL)

dbDisconnect(connection)

head(tbls$tbl_blob)
head(tbls$tbl_run)
head(tbls$tbl_step)
```

```{r}
#read Flow data
fss <- fread(paste0("fss_data_", VRSN, ".csv"))

head(fss) # Flow + importance items Q1-Q13, skill-demand items A1-A3 (not used here)
```

***
  
  ### Wrangling
  
  <br>
  <br>
  CogCarSim

```{r}
# remove extra (test) runs
tbl_run %<>% # %<>% operator overwrites dataframe
  filter(startsWith(participant, '0'))

# filter other tables with updated runs
tbl_blob %<>%
  filter(run %in% tbl_run$run)

tbl_step %<>%
  filter(run %in% tbl_run$run)

# assign table to modify data
game_data <- tbl_run %>%
  dplyr::select(-run) %>%
  
  # extract old participant variable into new participant, session, run variables
  tidyr::extract(participant, c('participant', 'session', 'run'),
                 "([[:alnum:]]+)-([[:alnum:]]+)-([[:alnum:]]+)") %>%
  mutate_at(vars(session,run), as.numeric) %>%
  
  # arrange rows to create cumulative run variable
  arrange(participant, session, run) %>%
  group_by(participant) %>%
  
  # also log(duration) and log(cumrun) variables for plotting
  mutate(cumrun = row_number(),
         ln.duration = log(duration),
         ln.cumrun = log(cumrun)) %>% 
  
  ungroup # remember to ungroup!

```

```{r}
head(game_data)
```
***
  <br>
  <br>
  Flow

```{r}
# indicate fss questions for flow factors: fluency, absorption, flow, perceived importance
fluency_items <- c('Q2', 'Q4', 'Q5', 'Q7', 'Q8', 'Q9')
abs_items <- c('Q1', 'Q3', 'Q6', 'Q10')
flow_items <- c(fluency_items, abs_items)
pi_items <- c('Q11', 'Q12', 'Q13')

# compute flow factors per run
fss_items <- fss %>%
  mutate(fluency = rowMeans(dplyr::select(., all_of(fluency_items))),
         absorption = rowMeans(dplyr::select(., all_of(abs_items))),
         flow = rowMeans(dplyr::select(., all_of(flow_items))),
         pi_total = rowMeans(dplyr::select(., all_of(pi_items)))) %>%
  
  # add also total perceived importance (mean)
  rename(pi1 = Q11,
         pi2 = Q12,
         pi3 = Q13) %>%
  dplyr::select(participant:run, fluency, absorption, flow, pi1:pi3, pi_total) %>%
  
  # mutate participant variable into the right format (1 -> "01")
  mutate(participant = paste0('0', as.character(participant)))

```

```{r}
head(fss_items)

# Basic violin plot
ggplot(fss_items, aes(x=participant, y=flow)) + 
  geom_half_violin(trim=FALSE, fill="gray", side = "r") +
  geom_boxplot(width=0.1, outlier.shape = NA) +
  geom_hline(yintercept = median(fss_items$flow), color = "red") +
  geom_text(aes(10, median(fss_items$flow), label = "med.Flow", vjust = -1)) +
  labs(title="Flow scores per participant", x="Participant", y = "Flow") +
  ylim(2, 7) +
  theme_classic()
ggsave(file.path(odir, "FlowXsubj.svg"))

```
***
  <br>
  <br>
  Merge CogCarSim and Flow data

```{r}
# join game data and fss data into a single dataframe
fss_game <- game_data %>%
  dplyr::select(participant:run, collisions, duration, ln.duration, distance, cumrun, ln.cumrun) %>%
  left_join(fss_items, by = c('participant', 'session', 'run')) # if no vars given, use the ones with identical names
```

```{r}
# display the datatable created just before
datatable(fss_game, filter='top', options = list(pageLength = 5, scrollX=T) )
```

<br>
  <br>
  Sanity check  
```{r}
# see if everything is as it should be (e.g. no leftover rows of data, sane amount of sessions etc.)
summary(fss_game)
```
***
  ### Extracting learning curve coefficients and predicted learning curves
  Fit a log-log regression curve for each participant separately: **log(duration) ~ log(cumulative run)** to get slope and intercept coefficients.  
```{r}
fss_learning <- fss_game %>%
  group_by(participant) %>%
  
  nest() %>% 
  # fit a linear model using log-log formula on durations and cumruns per participant
  mutate(fit = map(data, ~lm(ln.duration ~ ln.cumrun, data = .)), # make models and...
         coef = map(fit, tidy), # ...get coefficients and...
         data_aug = map(fit, augment)) %>% #...get predictions
  unnest(coef) %>%
  
  # predicted curve slope and interception
  select(participant, term, estimate, data_aug) %>%
  spread(term, estimate) %>%
  rename(slope = ln.cumrun,
         intercept = `(Intercept)`) %>%
  unnest(data_aug) %>%
  
  ungroup %>%
  
  # join new ones to fss_game -> fss_learning
  select(participant:.fitted, intercept, slope) %>%
  rename(learning_curve = .fitted) %>%
  left_join(fss_game, by = c('participant', 'ln.duration', 'ln.cumrun')) %>%
  select(participant, session, run, everything()) 

```

```{r}
# spit out newly created data
head(fss_learning)
```

```{r fig.height=8, fig.width=12}

# plot linear performance
ggplot(fss_learning, aes(cumrun, duration)) +
  geom_point(alpha=.6, size=2) +
  geom_smooth(method = "lm", se = FALSE, linetype = 1, size = 0.5, color="red") +
  facet_wrap(~participant) +
  theme_bw(base_size = 14)
ggsave(file.path(odir, "PerfXsubj.svg"))

# plot linear performance with power law fit
ggplot(fss_learning, aes(cumrun, duration)) +
  geom_point(alpha=.6, size=2) +
  stat_smooth(method = 'nls', formula = 'y~a*x^b', size = 0.5, se=FALSE, color ="red") +
  facet_wrap(~participant) +
  theme_bw(base_size = 14)
ggsave(file.path(odir, "PerfXsubj_powerlaw.svg"))

# acquire flow z-scores
fss_learning %<>% group_by(participant) %>% 
  mutate(z.flow = ((flow-mean(flow)) / sd(flow)))

# plot linear performance with power law fit and flow z-scores coloring
ggplot(fss_learning, aes(cumrun, duration, color = z.flow)) +
  geom_point(alpha=.6, size=2) +
  stat_smooth(method = 'nls', formula = 'y~a*x^b', size = 0.5, se=FALSE, color ="red") +
  facet_wrap(~participant) +
  scale_color_viridis() +
  theme_bw(base_size = 14)
ggsave(file.path(odir, "PerfXsubj_powlxFlow.svg"))

# plot log-log with flow z-scores coloring
ggplot(fss_learning, aes(ln.cumrun, ln.duration, color = z.flow)) +
  geom_point(alpha=.6, size=2) +
  geom_smooth(method = "lm", se = FALSE, linetype = 1, size = 0.5, color="red") +
  facet_wrap(~participant) +
  scale_color_viridis() +
  theme_bw(base_size = 14)
ggsave(file.path(odir, "PerfXsubj_powlxFlow_loglog.svg"))

# plot deviation from predicted curve
fss_learning <- mutate(fss_learning, deviation = ln.duration - learning_curve)
ggplot(fss_learning, aes(deviation, flow)) +
  geom_point(alpha=.6, size=2) +
  geom_smooth(method = "lm", se = FALSE) + 
  facet_wrap(~participant) +
  theme_bw(base_size = 14)
ggsave(file.path(odir, "FlowXdevXsubj.svg"))

# statistical test (linear mixed model)
fss_learning_lmer <- lmer(flow ~ deviation + (deviation|participant), data=fss_learning)
summary(fss_learning_lmer) # model summary
plot(fss_learning_lmer) # model diagnostics
qqnorm(residuals(fss_learning_lmer)) #qq-plot
qqline(residuals(fss_learning_lmer)) #line of "perfect normality"

```